### ISSUE TITLE
Severe: Not working with PNGs (screenshots in iOS)

### ISSUE THREAD

**Issue by msw333** [btastic/flutter_native_image#47]
When I am using the compressor with JPGs, it's all fine (I can upload everything to Firebase Storage). 

But it is not working with PNGs (simple screenshot from Smartphone). Any idea how to solve?

**Comment by btastic** [comment]
Can you give me a sample code which you are working on? I solely used png's to test the conversion.

**Comment by msw333** [comment]
![BCDAB986-FAD5-4818-8633-B172F8116E83](https://user-images.githubusercontent.com/46572127/57197439-93976d00-6f67-11e9-9966-99e29ccae53d.png)

Currently, I don’t have my Mac with me. Just try with a screenshot, taken on iPhone X (attached) + newest version of image picker (source gallery). Should not work.

**Comment by msw333** [comment]
My code looks like this 

`Future _getImageGallery() async {
    File imageFile = await ImagePicker.pickImage(source: ImageSource.gallery);
    FocusScope.of(context).requestFocus(new FocusNode());

    if (imageFile != null) {
      imageUpload(imageFile);
    }
  }`

`imageUpload(imageFile) async {
    ImageProperties properties =
        await FlutterNativeImage.getImageProperties(imageFile.path);
    File compressedFile = await FlutterNativeImage.compressImage(
        croppedFile.path,
        quality: quality,
        targetWidth: targetWidth,
        targetHeight:
            (properties.height * targetWidth / properties.width).round());
    String fileName = DateTime.now().millisecondsSinceEpoch.toString() + '.jpg';
    StorageReference reference = FirebaseStorage.instance
        .ref()
        .child('users')
        .child(widget.userId)
        .child('profileImage')
        .child(fileName);
    StorageUploadTask uploadTask = reference.putFile(compressedFile);
    StorageTaskSnapshot storageTaskSnapshot = await uploadTask.onComplete;
    await storageTaskSnapshot.ref.getDownloadURL().then((downloadUrl) {
      small
          ? this._avatarUrlSmall = downloadUrl
          : this._avatarUrl = downloadUrl;
    });
  }`

**Comment by btastic** [comment]
You are not awaiting the call to imageUpload(imageFile) in _getImageGallery()

**Comment by msw333** [comment]
Nope, does not work. It works with images but not with screenshots on iOS. Have you tried it with my image screenshot?

**Comment by btastic** [comment]
Not yet. I am currently quite busy with other projects. But I will try to do it this week.

**Comment by msw333** [comment]
Thanks a lot. Really waiting for a solution here ;-).

**Comment by msw333** [comment]
Hi Ben, have you found the bug?

**Comment by btastic** [comment]
I just tested it and cannot repro it with an android emulator.

I did not actually upload anything to a storage, but compressing works fine.

Here is a gist with the code I used:

https://gist.github.com/btastic/1f18997592870c0aa5dd27a3d48b35a4

**Comment by btastic** [comment]
Ohh I see now. The images are actually not compressed and there is an error in the console. Will have a look at that.

**Comment by msw333** [comment]
I have these issues in particular on iOS.

**Comment by btastic** [comment]
I just pushed https://github.com/btastic/flutter_native_image/commit/249357866afda4d9d41623a8152947fa19877836

please try it

**Comment by msw333** [comment]
Now it gives the following error for every image (tested on iOS):

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type 'int' is not a subtype of type 'String'
#0      FlutterNativeImage.getImageProperties (package:flutter_native_image/flutter_native_image.dart:46:59)
<asynchronous suspension>
#1      ChatScreenState.uploadFile (package:first_app/chats/chat_room/group_chats/chat_screen.dart:1017:30)
<asynchronous suspension>
#2      _ImageConfirmationScreenState.build.<anonymous closure> (package:first_app/image_gallery/image_confirmation_screen.dart:63:26)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:625:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:691:32)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:181:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:250:9)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:182:9)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:450:9)
#9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
#10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:100:11)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#16     _rootRunUnary (dart:async/zone.dart:1136:13)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _invoke1 (dart:ui/hooks.dart:234:10)
#20     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)`

**Comment by btastic** [comment]
Ah it was Late yesterday and I built the date feature on android. Did not think about ios. Will fix later

**Comment by msw333** [comment]
Perfect - thanks a lot. Hope you can upload it soon ;-)

**Comment by btastic** [comment]
Can you try it again? Just updated

**Comment by kervral** [comment]
Still got the same error on iOS 
Flutter doctor : `Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale fr-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.7)
[!] VS Code (version 1.33.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)`

Sample code : 
`  static Future<File> resize(File file) async {
    final ImageProperties properties = await FlutterNativeImage.getImageProperties(file.path);
    if (properties.height < 1000 || properties.width < 1000) {
      return Future<File>.value(file);
    }

    if (properties.height > properties.width) {
      return FlutterNativeImage.compressImage(file.path, quality: 80, targetHeight: (properties.height * 1000 / properties.width).round(), targetWidth: 1000);
    }

    return FlutterNativeImage.compressImage(file.path, quality: 80, targetHeight: 1000, targetWidth: (properties.width * 1000 / properties.height).round());
  }`

**Comment by btastic** [comment]
I need to debug this. I will probably revert the latest changes for now.

**Comment by btastic** [comment]
Changes are reverted now. Compressing images should still work, but I removed the exif datetime thing

**Comment by kervral** [comment]
Thanks, it works.

**Comment by mobilinked** [comment]
The compressed result file size is zero. Would you please help to suggest how can I get the "reverted" code into the project? I am using VS Code with flutter version 1.5

**Comment by btastic** [comment]
@mobilinked The changes in this PR literally solved thst problem. Did you upgrade the packages?

**Comment by mobilinked** [comment]
@btastic I think I may do something basis wrong, could you please help to check if my actions are right to refresh the package? 

- In the pubspec.yaml
flutter_native_image: 
    git: https://github.com/btastic/flutter_native_image.git

- Run
flutter packages upgrade

I may need to take another action to fetch the PR? 

Thanks

**Comment by btastic** [comment]
Looks good to me. You can try removing the package alltogether and readding it again.

**Comment by mobilinked** [comment]
Removed and then added all the packages in the pubspec, and tried "git rm -r --cached ." to remove the git cache. There is no luck.

The record related in the pubspec.lock file
--------------
flutter_native_image:
    dependency: "direct main"
    description:
      path: "."
      ref: HEAD
      resolved-ref: "249357866afda4d9d41623a8152947fa19877836"
      url: "https://github.com/btastic/flutter_native_image.git"
    source: git
    version: "0.0.4"
-------------------

The code works well before, which is like
`
// sourceImageFilePath -- is the picked image with png file extension
final ImageProperties properties = await FlutterNativeImage.getImageProperties(sourceImageFilePath);
      final thumbnailWidth = (properties.width * thumbnailHeight / properties.height).round();
      final File compressedFile = await FlutterNativeImage.compressImage(
        sourceImageFilePath,
        quality: 90,
        targetWidth: thumbnailWidth,
        targetHeight: thumbnailHeight,
      );

      await compressedFile.copy(thumbnailFilePath);
`
the result is that the compressed file (thumbnailFilePath) size is always zero.

Thanks much

**Comment by btastic** [comment]
Would you mind attaching the image you are trying to compress? You can also send it to "bkonsem at gmail dot com" if you don't want to post that picture publicly.

**Comment by btastic** [comment]
I received an email from @mobilinked with the image. But it just works with android.

@a-leblond @strokine Does one of you own a Mac + iPhone to test this?

Here is the image. Sorry but I put it in a zip file because I am scared that any image hoster will compress the image and change things: https://we.tl/t-PyWAkJIaI2

**Comment by mobilinked** [comment]
@btastic Tested on another Mac, same problem. 

But the code works well on the real devices - so the problem here is: 
- The compressed file size is zero on iOS simulator
- The code works well on the iPhone devices

Thanks.

**Comment by haibin2017** [comment]
I test it on iphone device,but not work, please check it @btastic 
flutter_native_image:
    dependency: "direct main"
    description:
      path: "."
      ref: HEAD
      resolved-ref: "249357866afda4d9d41623a8152947fa19877836"
      url: "https://github.com/btastic/flutter_native_image.git"
    source: git
    version: "0.0.4"

**Comment by btastic** [comment]
I am getting a mac to reproduce these issues. Sorry for leaving you hanging, but other projects / work + no mac makes it hard to tackle these kind of issues.

**Comment by btastic** [comment]
Okay I am finally able to reproduce the issue. It has to do with image with alpha channels. However, I am not an expert on image processing. I just stitched together this library and was happy that it was working so far.

As stated in the README file, I took the resizing code from Trevor at http://vocaro.com/trevor/blog/2009/10/12/resize-a-uiimage-the-right-way/comment-page-1/#comments, and you can see in the comments, there is one guy that has the same issue as we have in this library. I will pass a message to trevor and will try to debug again on the weekend to get more information.

**Comment by btastic** [comment]
https://stackoverflow.com/questions/42494745/why-do-iphone-7-and-iphone-7-plus-screenshots-send-an-incompatible-alpha-with-rg here are people that have the same issue, and a workaround.

**Comment by btastic** [comment]
Alright, I just pushed a fix on a different branch. Please change the your pubspec.yml as follows:

```
flutter_native_image:
  git:
    url: https://github.com/btastic/flutter_native_image.git
    ref: fix/ios_compression
```

Please let me know if this works for you and if you spot anything else.

**Comment by davicg** [comment]
Hey @btastic , tested your fix in iOS and its working perfectly! I was finding this issue in all screenshots and downloaded PNG files. Good job! Can't wait until it's merged on master!

**Comment by davicg** [comment]
> Alright, I just pushed a fix on a different branch. Please change the your pubspec.yml as follows:
> 
> ```
> flutter_native_image:
>   git:
>     url: https://github.com/btastic/flutter_native_image.git
>     ref: fix/ios_compression
> ```
> 
> Please let me know if this works for you and if you spot anything else.

Hey @btastic , tested your fix in iOS and its working perfectly! I was finding this issue in all screenshots and downloaded PNG files. Good job! Can't wait until it's merged on master!

**Comment by JamesMcIntosh** [comment]
@btastic Are you going to merge the branch `fix/ios_compression` into master?

**Comment by btastic** [comment]
Just merged it..

**Comment by iNima** [comment]
Hi @btastic 
I have the same issue with the screenshots in iOS.
I just checked the master branch but it seems that the fix has not been merged to the master.
I think the fix has been implemented in this commit but it is not in the master.
https://github.com/btastic/flutter_native_image/commit/e8aec353fb23186ac5858ef1263e4e2b1a358ff0

Could you please double-check it and merge the fix if possible?

Thanks
Nima

**Comment by DeanPack** [comment]
same, this bug doesn't appear to be fixed.

**Comment by DeanPack** [comment]
even though I cherry pick your commit, it doesn't work. Here is my pubspec.lock
  flutter_native_image:
    dependency: "direct main"
    description:
      path: "."
      ref: "fix/ios_compression"
      resolved-ref: "3c5890268c56cc0398bd0be1939403be2a27906b"
      url: "https://github.com/btastic/flutter_native_image.git"
    source: git
    version: "0.0.4"

**Comment by btastic** [comment]
I just merged #69, I accidently merged master -> fix/ios_compression. I had to merge the other way around. Whoops! Can you check it works on master? I'll create a new pub.dev release when it is working.

Thanks!

**Comment by DeanPack** [comment]
even though I put in master branch, I'm still getting your most recent version in my pub cache, even though I deleted it and rebuilt it.
  flutter_native_image:
    git:
      url: https://github.com/btastic/flutter_native_image.git
      ref: master

this is from my flutter pub get
Downloading flutter_native_image 0.0.5+2...

**Comment by btastic** [comment]
I wonder if @davicg can check again to confirm it is still working? I don't have an iOS device anymore so I cant test :/

**Comment by DeanPack** [comment]
I know pub cache is really finicky. Someone smarter than me will be starting work soon and I'll see what he can do to help me get your master branch

**Comment by DeanPack** [comment]
I still cannot get your master branch.

**Comment by DeanPack** [comment]
ok. turns out I am getting the master branch properly, but there was another error causing me grief. Recently ios has changed how they handle file paths somehow. I had to change my paths from
`      videoPath = join(
        (await getTemporaryDirectory()).path,
        '${DateTime.now()}.mp4',
      );`
to
`      videoPath = join(
        (await getTemporaryDirectory()).path,
        '${DateTime.now().toIso8601String()}.mp4',
      );`
I have images working now. go for the new version!

**Comment by FabianDean** [comment]
> ok. turns out I am getting the master branch properly, but there was another error causing me grief. Recently ios has changed how they handle file paths somehow. I had to change my paths from
> ` videoPath = join( (await getTemporaryDirectory()).path, '${DateTime.now()}.mp4', );`
> to
> ` videoPath = join( (await getTemporaryDirectory()).path, '${DateTime.now().toIso8601String()}.mp4', );`
> I have images working now. go for the new version!

Thank you!! I've been racking my brain for the past two days trying to figure out this bug I was having with cropImage() (I know this thread's for compressImage()). I was trying all sorts of things with no luck, and this change in the path finally fixed my issue! If I may, how did you come to this solution?

**Comment by DeanPack** [comment]
> Thank you!! I've been racking my brain for the past two days trying to figure out this bug I was having with cropImage() (I know this thread's for compressImage()). I was trying all sorts of things with no luck, and this change in the path finally fixed my issue! If I may, how did you come to this solution?

I found the solution elsewhere on a google search.
